    // header section

    var headerSection = document.createElement("header");
    headerSection.classList.add("header-section");
        var homeLink = document.createElement("div");
        homeLink.classList.add("header-section__home-link");
            var home = document.createElement("div");
            home.classList.add("header-section__home-link__home");
                var menuSizeImg = document.createElement("div");
                menuSizeImg.classList.add("header-section__home-link__home__menu-size-img");
                    var menuImg = document.createElement("img");
                    menuImg.classList.add("header-section__home-link__home__menu-size-img__menu-img");
                        var menuImgAttribute = { "src" : "./assets/icons/hamburger-menu.png", "alt" : "Menu-Image"};
                        setCollection(menuImg, menuImgAttribute);
                var homeImg = document.createElement("div");
                homeImg.classList.add("header-section__home-link__home__homeImg")
                    var clockifyImg = document.createElement("img");
                    clockifyImg.classList.add("header-section__home-link__home__homeImg__clockify-img");
                        var clockifyImgAttribute = { "src" : "./assets/icons/clockify-logo.svg", "alt" : "Clockify-logo"};
                        setCollection(clockifyImg, clockifyImgAttribute);
            var account = document.createElement("div");
            account.classList.add("header-section__account");
                var workspace = document.createElement("div");
                workspace.classList.add("header-section__account__workspace");
                    var selectedWorkspace = document.createElement("div");
                    selectedWorkspace.classList.add("header-section__account__workspace__selected-workspace");
                    selectedWorkspace.textContent = "USER's workspace";
                    var workspaceDropdown = document.createElement("select");
                    workspaceDropdown.classList.add("header-section__account__workspace__drop-down");
                    var workspaceMenu = document.createElement("div");
                    workspaceMenu.classList.add("header-section__account__workspace__workspace-menu");
                        var workspaceMenuTitle = document.createElement("div");
                        workspaceMenuTitle.classList.add("header-section__account__workspace__workspace-menu__workspace-title");
                            workspaceMenuTitle.innerHTML = `<div class='header-section__account__workspace__workspace-menu__workspace-title__head'>WORKSPACES</div><div class='header-section__account__workspace__workspace-menu__workspace-title__manage'>Manage</div>`;
                        var workspaceComponent = document.createElement("div");
                        workspaceComponent.classList.add("header-section__account__workspace__workspace-menu__workspace-component");
                            var workspaceTxt = document.createElement("div");
                            workspaceTxt.classList.add("header-section__account__workspace__workspace-menu__workspace-component__txt");
                            workspaceTxt.textContent = "USER's workspace";
                            var workspaceActive = document.createElement("div");
                            workspaceActive.classList.add("header-section__account__workspace__workspace-menu__workspace-active");
                                workspaceActive.innerHTML = `<img src='./assets/icons/checkmark-green.svg' alt='green-mark-icon' class='header-section__account__workspace__workspace-menu__workspace-active__img'/><div class='header-section__account__workspace__workspace-menu__workspace-active__txt'>Active</div>`;
                var plan = document.createElement("div");
                plan.classList.add("header-section__account__plan");
                    var planBtn = document.createElement("button");
                    planBtn.classList.add("header-section__account__plan__upgrade-btn");
                    planBtn.innerHTML = `UPGRADE`;
                var help = document.createElement("div");
                help.classList.add("header-section__account__help");
                    var queryImg = document.createElement("img");
                    queryImg.classList.add("header-section__account__help__query-img");
                        var queryImgAttribute = { "src" : "./assets/icons/Help options.svg", "alt" : "Help-Image"};
                        setCollection(queryImg, queryImgAttribute);
                var notification = document.createElement("div");
                notification.classList.add("header-section__account__notification");
                    var bellImg = document.createElement("img");
                    bellImg.classList.add("header-section__account__notification__bell-img");
                        var bellImgAttribute = { "src" : "./assets/icons/View notifications.svg", "alt" : "Notification-Image"};
                        setCollection(bellImg, bellImgAttribute);
                var profile = document.createElement("div");
                profile.classList.add("header-section__account__profile");
                    var profileImg = document.createElement("img");
                    profileImg.classList.add("header-section__account__profile__profile-img");
                        var profileImgAttribute = { "src" : "./assets/icons/user.png", "alt" : "Profile-Pic"};
                        setCollection(profileImg, profileImgAttribute);

    clockify.appendChild(headerSection);
        headerSection.appendChild(homeLink);
            homeLink.appendChild(home);
                home.appendChild(menuSizeImg);
                    menuSizeImg.appendChild(menuImg);
                home.appendChild(homeImg);
                    homeImg.appendChild(clockifyImg)
        headerSection.appendChild(account);
            account.appendChild(workspace);
                workspace.appendChild(selectedWorkspace);
                workspace.appendChild(workspaceDropdown);
                workspace.appendChild(workspaceMenu);
                    workspaceMenu.appendChild(workspaceMenuTitle);
                    workspaceMenu.appendChild(workspaceComponent);
                        workspaceComponent.appendChild(workspaceTxt);
                        workspaceComponent.appendChild(workspaceActive);
            account.appendChild(plan);
                plan.appendChild(planBtn);
            account.appendChild(help);
                help.appendChild(queryImg);
            account.appendChild(notification);
                notification.appendChild(bellImg);
            account.appendChild(profile);
                profile.appendChild(profileImg);
